name: Pre-compiled PyROOT 

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev tar gfortran subversion make rsync
        pip install -r tests/requirements.txt
    - name: Check Python version
      run: python --version

    - name: Install ROOT
      run: |
        wget https://root.cern/download/root_v6.24.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        tar -xzvf root_v6.24.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        source root/bin/thisroot.sh
    
    - name: Test environment variables
      run: |
        source root/bin/thisroot.sh
        python tests/test_root.py
    - name: Check library
      run: |
        pwd
        ls
        find root/lib -name "libcppyy3_8*"
        ls root/lib

    - name: Run script
      run: |
        source root/bin/thisroot.sh
        pytest tests
