name: Pre-compiled PyROOT 

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev tar gfortran subversion make rsync
        pip install -r tests/requirements.txt
    - name: Check Python version
      run: python --version

    - name: Install ROOT
      run: |
        wget https://root.cern/download/root_v6.24.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        tar -xzvf root_v6.24.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        source root/bin/thisroot.sh
    
    - name: Test environment variables
      run: |
        source root/bin/thisroot.sh
        python tests/test_root.py
    - name: Check library
      run: |
        pwd
        ls
        find root/lib -name "libcppyy3_8*"
        ls root/lib

    - name: Install Madgraph5
      run: |
        wget https://launchpad.net/mg5amcnlo/3.0/3.3.x/+download/MG5_aMC_v3.3.2.tar.gz
        mkdir madgraph5
        tar xf MG5_aMC_v3.3.2.tar.gz --strip=1 --directory=madgraph5
    
    - name: Install Pythia8 & Delphes in Madgraph5
      run: |
        source root/bin/thisroot.sh
        cd madgraph5
        ./bin/mg5_aMC << EOF
        install pythia8
        install Delphes
        quit
        EOF

    - name: Run tests and collect coverage
      run: |
        source root/bin/thisroot.sh
        pytest tests --cov --cov-report=xml

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3